apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: social-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: social-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: social-app
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432