name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: |
          cd backend
          docker build -t mstojanoska/kiii-backend:latest .

      - name: Build frontend image
        run: |
          cd frontend
          docker build -t mstojanoska/kiii-frontend:latest .

      - name: Push backend image
        run: |
          docker push mstojanoska/kiii-backend:latest

      - name: Push frontend image
        run: |
          docker push mstojanoska/kiii-frontend:latest